<?php

namespace rnpagebuilder\PageGenerator\Core\Area;

use rnpagebuilder\core\Exception\FriendlyException;
use rnpagebuilder\DTO\ConditionGroupOptionsDTO;
use rnpagebuilder\DTO\ConditionLineOptionsDTO;
use rnpagebuilder\DTO\ConditionTypeEnumDTO;
use rnpagebuilder\PageGenerator\Core\QueryBuilder\Comparison\FixedValueComparison;
use rnpagebuilder\PageGenerator\Core\QueryBuilder\Filters\FilterGroup;
use rnpagebuilder\PageGenerator\Core\QueryBuilder\Filters\FilterLineBase;
use rnpagebuilder\PageGenerator\Managers\MessageManager;
use Twig\Markup;

class SingleViewPageArea extends PageAreaBase
{
    public function MaybeUpdateDataSource()
    {


        $entryId=intval($this->PageGenerator->GetGetParameter('entryid'));


        if(!wp_verify_nonce($this->PageGenerator->GetGetParameter('nonce'),$this->PageGenerator->Options->Id.'_'.$this->PageGenerator->Options->FormId.'_'.$entryId.'_view'))
            throw new FriendlyException('Invalid request, please try again');


        $condition=(new ConditionGroupOptionsDTO())->Merge();
        $condition->ConditionLines=[(new ConditionLineOptionsDTO())->Merge()];
        $condition->ConditionLines[0]->FieldId='__entryId';
        $condition->ConditionLines[0]->Comparison='Equal';
        $condition->ConditionLines[0]->PathId='';
        $condition->ConditionLines[0]->Type=ConditionTypeEnumDTO::$Filter;
        $condition->ConditionLines[0]->SubType='EntryId';
        $condition->ConditionLines[0]->Value=$entryId;
        $this->PageGenerator->AddAdditionalFilters($condition);
        parent::MaybeUpdateDataSource(); // TODO: Change the autogenerated stub
    }

    public function Render()
    {
        if($this->PageGenerator->EntryRetriever->GetCurrentRow()==null)
            return new Markup(MessageManager::ShowErrorMessage('Sorry the entry was not found','rnpagebuilder'),'UTF-8');
        return parent::Render(); // TODO: Change the autogenerated stub
    }


}