<?php

namespace rnpagebuilder\PageGenerator\Blocks\NavigationBlock;

use rnpagebuilder\DTO\FieldBlockOptionsDTO;
use rnpagebuilder\PageGenerator\Blocks\Core\BlockBase;

class NavigationBlock extends BlockBase
{
    /** @var FieldBlockOptionsDTO */
    public $Options;

    public $TotalRows=0;
    public $CurrentPage=0;

    protected function BeforeRender()
    {
        parent::BeforeRender(); // TODO: Change the autogenerated stub
        $this->TotalRows=$this->GetEntryRetriever()->GetTotalRows();
        $this->CurrentPage=$this->GetPageGenerator()->GetCurrentPage();
    }

    public function GetIsFirstPage(){
        return $this->CurrentPage==0;
    }

    public function GetIsLastPage(){
        return $this->CurrentPage==$this->GetTotalNumberOfPages()-1||$this->GetTotalNumberOfPages()==0;
    }

    public function GetCurrentPage(){
        return $this->GetPageGenerator()->GetCurrentPage();
    }

    public function GetTotalNumberOfPages(){
        return $this->GetPageGenerator()->GetTotalNumberOfPages();
    }

    protected function GetTemplateName()
    {
        return 'PageGenerator/Blocks/NavigationBlock/NavigationBlock.twig';
    }

}