<?php


namespace rnpagebuilder\core\Integration\Processors\Settings\Forms\Fields;


class DateTimeFieldSettings extends FieldSettingsBase
{
    public $DateFormat;
    public $TimeFormat;
    public $Mode='DateTime';


    public function __construct()
    {
        parent::__construct();
        $this->RendererType='Text';

    }

    public function SetDateTimeMode()
    {
        $this->Mode='DateTime';
        return $this;
    }

    public function SetTimeMode(){
        $this->Mode='Time';
        return $this;
    }

    public function SetDateMode(){
        $this->Mode='Date';
        return $this;
    }

    public function ParseStringValue($value, $pathId = null)
    {
        return parent::ParseStringValue($value, $pathId); // TODO: Change the autogenerated stub
    }


    public function SetDateFormat($dateFormat){
        $this->DateFormat=$dateFormat;
        return $this;
    }

    public function SetTimeFormat($timeFormat)
    {
        $this->TimeFormat=$timeFormat;
        return $this;
    }

    public function InitializeFromOptions($options)
    {
        $this->DateFormat=$this->GetStringValue($options,'DateFormat');
        $this->TimeFormat=$this->GetStringValue($options,'TimeFormat');

        parent::InitializeFromOptions($options); // TODO: Change the autogenerated stub
    }


    public function GetType()
    {
        return 'DateTime';
    }

}