<?php

namespace rnpagebuilder\core\Integration\Processors\Settings\Forms\Fields;

use Twig\Markup;

class LikertScaleFieldSettings extends FieldSettingsBase
{
    public $Rows=[];
    public $Columns=[];

    public function GetType()
    {
        return 'LikertScale';
    }

    public function AddRows($rows)
    {
        if(is_array($rows))
            $this->Rows=$rows;
    }

    public function AddColumns($columns)
    {
        if(is_array($columns))
            $this->Columns=$columns;
    }

    public function ParseHTMLValue($value, $pathId = null)
    {
        return new Markup(nl2br($value->value),'UTF-8');// TODO: Change the autogenerated stub
    }


}