<?php

namespace rnpagebuilder\PageGenerator\TextRenderer\Core;;

class SimpleContainerTextRenderer extends TextRendererBase
{
    public $TagToUse;
    public function __construct($tagToUse,$content, $parent = null,$pageGenerator=null)
    {
        $this->TagToUse=$tagToUse;
        parent::__construct($content, $parent,$pageGenerator);
    }


    protected function GetTemplateName()
    {
        return 'PageGenerator/TextRenderer/Core/SimpleContainerTextRenderer.twig';
    }

    public function GetAlignment(){
        if(!isset($this->Content->attrs))
            return '';
        switch ($this->Content->attrs->align)
        {
            case 'left':
                return 'left';
            case 'right':
                return 'right';
            case 'center':
                return 'center';
            default:
                return '';
        }
    }

    protected function InternalInitialize()
    {
        parent::InternalInitialize(); // TODO: Change the autogenerated stub
    }


}